function [Y,Xf,Af] = nn_mesh_size_naca_21(X,~,~)
%NN_MESH_SIZE_NACA_21 neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 25-Jan-2021 16:14:58.
% 
% [Y] = nn_mesh_size_naca_21(X,~,~) takes these arguments:
% 
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = 1xQ matrix, input #1 at timestep ts.
% 
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = 1xQ matrix, output #1 at timestep ts.
% 
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1_xoffset = 0;
x1_step1_gain = 1.5088069425431;
x1_step1_ymin = -1;

% Layer 1
b1 = [3.1200191328013491;3.2670344330657586;-3.04401630010977;-1.0554540731992328;-0.10073695769441755;0.10133217440210668;-1.3509742892202834;2.1712825176674619;-1.9917814352778045;-2.6585071937050979];
IW1_1 = [-2.6378123945568563;-3.6385985622978816;5.089339059707485;4.675350537737395;-3.365409351690952;5.8103117539291915;-5.6301691407953669;3.6624477487786313;-2.5060935735986045;-2.5793404516292475];

% Layer 2
b2 = -0.28275372388543141;
LW2_1 = [1.1857563870115924 -0.46888255117810185 0.27346512715131222 0.69568673053281893 1.7539823471895775 0.85289990409340199 -0.60866499273068109 0.5358061686571175 0.34794314455344622 0.58011285303511761];

% Output 1
y1_step1_ymin = -1;
y1_step1_gain = 2.22453442656367;
y1_step1_xoffset = 0.323266012932347;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX, X = {X}; end;

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},2); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS

    % Input 1
    Xp1 = mapminmax_apply(X{1,ts},x1_step1_gain,x1_step1_xoffset,x1_step1_ymin);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1_gain,y1_step1_xoffset,y1_step1_ymin);
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX, Y = cell2mat(Y); end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings_gain,settings_xoffset,settings_ymin)
y = bsxfun(@minus,x,settings_xoffset);
y = bsxfun(@times,y,settings_gain);
y = bsxfun(@plus,y,settings_ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings_gain,settings_xoffset,settings_ymin)
x = bsxfun(@minus,y,settings_ymin);
x = bsxfun(@rdivide,x,settings_gain);
x = bsxfun(@plus,x,settings_xoffset);
end
