function [Y,Xf,Af] = nn_mesh_size_naca_4(X,~,~)
%NN_MESH_SIZE_NACA_4 neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 25-Jan-2021 16:44:08.
% 
% [Y] = nn_mesh_size_naca_4(X,~,~) takes these arguments:
% 
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = 1xQ matrix, input #1 at timestep ts.
% 
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = 1xQ matrix, output #1 at timestep ts.
% 
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1_xoffset = 0;
x1_step1_gain = 2.00345633024112;
x1_step1_ymin = -1;

% Layer 1
b1 = [6.5688249702535666;16.79367209101056;14.718276086422962;15.980870955948765;-0.55837973468013835;-1.8416778087924877;1.6224167285229691;-3.2671042708755622;3.4515824746012767;1.8589229031843837];
IW1_1 = [-7.3364224685244759;-27.856503853814658;-25.012382173571758;-27.840742930933242;0.80533583162059463;-11.28130699857072;9.2343006873675204;-8.6376571829757758;6.5864504769230328;4.2428128621021033];

% Layer 2
b2 = 0.80374999929992208;
LW2_1 = [0.28097088502309281 -4.258502290134567 8.9206894092743791 -4.3549987461042043 2.5517398480944187 1.5301672146954777 2.4354501103162991 -1.4379244566967326 2.3659917704108402 -5.1223537233251157];

% Output 1
y1_step1_ymin = -1;
y1_step1_gain = 2.45014430013268;
y1_step1_xoffset = 0.338695799732718;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX, X = {X}; end;

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},2); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS

    % Input 1
    Xp1 = mapminmax_apply(X{1,ts},x1_step1_gain,x1_step1_xoffset,x1_step1_ymin);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1_gain,y1_step1_xoffset,y1_step1_ymin);
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX, Y = cell2mat(Y); end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings_gain,settings_xoffset,settings_ymin)
y = bsxfun(@minus,x,settings_xoffset);
y = bsxfun(@times,y,settings_gain);
y = bsxfun(@plus,y,settings_ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings_gain,settings_xoffset,settings_ymin)
x = bsxfun(@minus,y,settings_ymin);
x = bsxfun(@rdivide,x,settings_gain);
x = bsxfun(@plus,x,settings_xoffset);
end
